plugins {
    id 'java'
    id 'com.gradleup.shadow' version '8.3.5'
}

group = 'pl.foxmoderation'
version = '1.0.0'

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
    maven { url = 'https://repo.lucko.me/' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.4-R0.1-SNAPSHOT'
    compileOnly 'net.luckperms:api:5.4'
    implementation 'org.xerial:sqlite-jdbc:3.50.3.0'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

processResources {
    filteringCharset = 'UTF-8'
    filesMatching('plugin.yml') {
        expand(version: project.version)
    }
}

build.dependsOn shadowJar
shadowJar {
    archiveClassifier = ''
}
